remote_theme: carlosperate/jekyll-theme-rtd
title: sc
description: Service Commander for IBM i
hljs_style: github-gist
repo_url: https://github.com/ThePrez/ServiceCommander-IBMi
collapse_navigation: true
include_homepage_in_sidebar: false
binclude:
  - quickstart/HANDS_ON.md
  - CONTRIBUTING.md
