remote_theme: carlosperate/jekyll-theme-rtd
title: sc
description: Service Commander for IBM i
search_enabled: true
hljs_style: github-gist
include:
  - README.md
  - CONTRIBUTING.md
  - quickstart/HANDS_ON.md
